@startuml CasosDeUso
left to right direction
actor "Usuário" as A1
actor "Sistema" as A2 

rectangle AstroPlayer {
  usecase "Upload de música" as UC1
  usecase "Gerenciar informações da música" as UC2
  usecase "Pesquisar músicas" as UC3
  usecase "Controlar música (reproduzir, pausar, pular, voltar, alterar volume)" as UC4
  usecase "Criar playlist" as UC5
  usecase "Personalizar playlist" as UC6
  usecase "Adicionar e remover músicas" as UC7
  usecase "Verificar estatísticas de uso" as UC9
  usecase "Registrar estatísticas de uso" as UC10
  usecase "Fornecer estatísticas de uso" as UC11

  (UC1) .> (UC2) : <<include>>
  (UC4) .> (UC10) : <<include>> 
  (UC9) .> (UC11) : <<include>> 
  (UC5) .> (UC7) : <<include>>  
  (UC5) .> (UC6) : <<include>>  
}

A1 --> UC1
A1 --> UC2
A1 --> UC3
A1 --> UC4
A1 --> UC5
A1 --> UC6
A1 --> UC7
A1 --> UC9

UC10 --> A2
UC11 --> A2
@enduml
